FROM python:alpine3.12

WORKDIR /src

COPY ./src/requirements.txt /src 
RUN pip install -r requirements.txt

# RUN gcloud auth application-default login

COPY ./src /src 

EXPOSE 5000

ENV FLASK_APP=app

CMD ["flask", "--app" "main.py" "--debug" "run"]